language: java
sudo: required
dist: xenial
jdk:
  - openjdk8
cache:
  directories:
    - "${HOME}/.m2"
branches:
  only:
    - master
script:
  - mvn install -Pintegration-tests
notifications:
  email:
    - amcp@amazon.com
